#+TITLE: Bobby Burden III's Emacs Configuration File

* Configuration
** MacOS Specific Changes
#+BEGIN_SRC emacs-lisp
  (setq mac-command-modifier 'ctrl
        mac-option-modifier 'meta
        mac-control-modifier 'super)
#+END_SRC

** Personal Information
#+BEGIN_SRC emacs-lisp
  (setq user-full-name "Bobby Burden III"
        user-mail-address "bobby@brb3.org")
#+END_SRC

** Backups
#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist '(("." . "~/.emacs.d/backups"))
        delete-old-versions -1
        version-control t
        vc-make-backup-files t
        auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-save-list/" t)))
#+END_SRC

Make sure that =tramp= keeps its backups locally
#+BEGIN_SRC emacs-lisp
  (setq tramp-backup-directory-alist backup-directory-alist)
#+END_SRC

** Visual Changes
We don't need no stinking window chrome
#+BEGIN_SRC emacs-lisp
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (setq fill-column 80)
#+END_SRC

Make org-mode look a little nicer, and build agendas correctly. Oh, and also
open directories in dired and follow links when I hit <RET>
#+BEGIN_SRC emacs-lisp
  (setq org-ellipsis " […]"
        org-hide-leading-stars t
        org-return-follows-links t
        org-agenda-files '("~/Documents/orgs/"
                           "~/Documents/orgs/UPS/"
                           "~/Documents/orgs/UPS/Magento"))

  (add-to-list 'org-file-apps '(directory . emacs))
#+END_SRC

This makes re-centering (<C-l>) go "top-middle-bottom"
#+BEGIN_SRC emacs-lisp
  (setq recenter-positions '(top middle bottom))
#+END_SRC

** Development
*** PHP
Make geben listen to port 9001i
#+BEGIN_SRC emacs-lisp
(setq dbgp-default-port 9001)
#+END_SRC

Turn off flycheck-mode
#+BEGIN_SRC emacs-lisp
(setq flycheck-global-modes '(not php-mode))
#+END_SRC

Here, I copy some of the changes from [[http://www.blogbyben.com/2016/08/emacs-php-modern-and-far-more-complete.html][this blog post]] by Ben Simon.
This enables [[https://www.gnu.org/software/emacs/manual/html_node/ccmode/Subword-Movement.html][subword-mode]], and turns off template compatibility, and
verifies some formatting settings.

#+BEGIN_SRC emacs-lisp
(defun brb3-php-mode-hook ()
       (auto-complete-mode t)
       (yas-global-mode 1)
       (require 'ac-php)
       (setq indent-tabs-mode nil
             c-basic-offset 4
             php-template-compatibility nil
             subword-mode 1
             ac-sources '(ac-source-php)))

(add-hook 'php-mode-hook 'brb3-php-mode-hook)
#+END_SRC

Next, also inspired by Ben Simon's blog post, we setup web-mode to use
with template files (=.phtml=). Also, configured =<f5>= to quickly
toggle between the two modes.

#+BEGIN_SRC emacs-lisp
(defun brb3-web-mode-hook ()
       (setq indent-tabs-mode nil
             web-mode-markup-indent-offset 4
             web-mode-css-indent-offset 4
             web-mode-code-indent-offset 4))

(add-hook 'web-mode-hook 'brb3-web-mode-hook)

(defun toggle-php-flavor-mode ()
       (interactive)
       "Toggle mode between php-mode & web-mode"
       (cond ((eq major-mode 'php-mode)
              (web-mode))
             ((eq major-mode 'web-mode)
              (php-mode))))

(global-set-key [f5] 'toggle-php-flavor-mode)
#+END_SRC

*** Magit
Turn on =magit-gh-pulls=.
#+BEGIN_SRC emacs-lisp
  (add-hook 'magit-mode-hook 'turn-on-magit-gh-pulls)
#+END_SRC

** Misc
*** Sentences should end with a single space.
#+BEGIN_SRC emacs-lisp
  (setq sentence-end-double-space nil)
#+END_SRC

*** org-page Configuration for [[https://brb3.org/][brb3.org]]
#+BEGIN_SRC emacs-lisp
  (setq op/repository-directory "~/Sites/brb3.dev/"
        op/personal-disqus-shortname "brb3"
        op/personal-google-analytics-id "UA-31681523-1"
        op/personal-github-link "https://github.com/brb3"
        op/personal-avatar "https://www.gravatar.com/avatar/md5sumOfYourEmailAddress"
        op/site-domain "https://brb3.org/"
        op/site-main-title "brb3://"
        op/site-sub-title "Bobby Burden III - Software Developer")
#+END_SRC

*** Pop to mark
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x p") 'pop-to-mark-command)
  (setq set-mark-command-repeat-pop t)
#+END_SRC

*** Shorten Yes/No prompts
#+BEGIN_SRC emacs-lisp
  (fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

*** Why would you ever leave Emacs?
#+BEGIN_SRC emacs-lisp
  (global-unset-key (kbd "C-x C-c"))
#+END_SRC

*** Enable deactivated commands
I'm not sure if this is necessary with Prelude, but I'm doing it anyway
#+BEGIN_SRC emacs-lisp
  (setq disabled-command-function nil)
#+END_SRC
